GitHub Actions build script and warning + Android Studio build instructions.
VendroidEnhanced/Vendroid pull request #3
Opened 2024-04-28 21:58 UTC by slotmachinedev

Took me too long.

2024-04-28 22:05 UTC, nin0-dev commented
best commit names I've ever seen :trollface: 

will review soon™

2024-04-28 22:08 UTC, slotmachinedev commented
I will never touch GitHub Actions scripts ever again.

2024-04-29 02:03 UTC, nin0-dev requested changes

2024-04-29 02:03 UTC, nin0-dev commented on .github/workflows/android.yml
> +      - 'release/**'
```suggestion
      - '*'
      - '!main'
```
this should trigger the workflow on all branches except main, which'll trigger another one

2024-04-29 02:04 UTC, nin0-dev approved these changes

2024-04-29 02:05 UTC, merged